### ISSUE TITLE
Saving Issue

### ISSUE THREAD

**Issue by SPARKY-00** [MusheAbdulHakim/Smarthr---hr-payroll-project-employee-management-System-Clone#2]
i am not able to save files in admin panel.

**Comment by MusheAbdulHakim** [comment]
Please give a more detail explanation of your issue. 
Like screenshots or even code. If you can't save files is probably because there's no write permission for the storage folder. Make sure the storage folder has write permission

**Comment by mashhour1234** [comment]
i tested it there are many page not found example leavetype.php and notification page and chat page .....etc

**Comment by MusheAbdulHakim** [comment]
sorry but we don't have the chat feature yet. And also the leave type page is there with the employee leaves.
![Screenshot at 2023-02-12 16-49-43](https://user-images.githubusercontent.com/58814410/218324968-aa2d1573-01f9-40eb-88dd-50d500cd9ea7.png)

**Comment by MusheAbdulHakim** [comment]
If you are facing any technical issues (like bugs or code errors), feel free to reopen this issue.
