### ISSUE TITLE
Complete Issues on Smarthr-hr-payroll-project-employee-management-System

### ISSUE THREAD

**Issue by saiapex2022** [MusheAbdulHakim/Smarthr---hr-payroll-project-employee-management-System-Clone#3]
Hello Sir,
The Software is not working of any options so please help me 

Regards,
Bijay K Nayak
info@saiapex.in
+91-9272697269

**Comment by MusheAbdulHakim** [comment]
Can you be more precise. Please provide details on the issue you are facing.
You can also try using the laravel version which has more features and up to date.
link: https://github.com/MusheAbdulHakim/Laravel-Smarthr
