### ISSUE TITLE
saving issue

### ISSUE THREAD

**Issue by chamous** [MusheAbdulHakim/Smarthr---hr-payroll-project-employee-management-System-Clone#4]
saving issue : for example when trying to add Department

**Comment by MusheAbdulHakim** [comment]
Can you add more information on your issue?. Maybe a screenshot or explain the exact error you are getting.

**Comment by chamous** [comment]
[](url)
![issue](https://user-images.githubusercontent.com/7762331/212746687-72883bb6-2646-4207-a66e-2992f09ed07c.png)

**Comment by chamous** [comment]
here i am trying to add a new department when clic on add this error appear

**Comment by MusheAbdulHakim** [comment]
did you import and setup the database?.

**Comment by chamous** [comment]
Yes i Did Bro

**Comment by chamous** [comment]
solved, you need to update the sql file

**Comment by MusheAbdulHakim** [comment]
ok.

**Comment by MusheAbdulHakim** [comment]
This project has been moved to laravel. The laravel version is more updated and is the one I mostly update.

**Comment by chamous** [comment]
Can i push the changes?

**Comment by MusheAbdulHakim** [comment]
yes your PR is welcome.
