### ISSUE TITLE
i tested it there are many page not found example leavetype.php and notification page and chat page .....etc

### ISSUE THREAD

**Issue by mashhour1234** [MusheAbdulHakim/Smarthr---hr-payroll-project-employee-management-System-Clone#5]
i tested it there are many page not found example leavetype.php and notification page and chat page .....etc

_Originally posted by @mashhour1234 in https://github.com/MusheAbdulHakim/Smarthr-hr-payroll-project-employee-management-System/issues/2#issuecomment-1426905847_

**Comment by MusheAbdulHakim** [comment]
Hi @mashhour1234 
This repo doesn't contain much features. Most of the features are in the Laravel version. You can find it here: https://github.com/MusheAbdulHakim/Laravel-Smarthr
If you're not able to find any page, it means, I haven't work on it yet.
Feel free to open this again if you're having bugs or something isn't working and is giving you any errors.
